apiVersion: v1
kind: Agent
base:
  model: qwen-plus
  framework: agno
mcp_servers:
- name: web_search
  command: uvx
  args:
  - mcp-server-fetch
agents:
- name: assistant
  instruction: You are a helpful AI assistant that can search the web and provide
    comprehensive answers.
  servers:
  - web_search
secrets:
- name: OPENAI_API_KEY
  value: sk-...
- name: OPENAI_BASE_URL
  value: https://dashscope.aliyuncs.com/compatible-mode/v1
